live:
  - name: Polygon RPC
    networks:
      - name: Mainnet
        chainid: 137
        id: polygon
        host:  https://speedy-nodes-nyc.moralis.io/cede2bf2868b0e93070abef2/polygon/mainnet/archive
        explorer: https://api.polygonscan.com/api

live:
  - name: Polygon Tenderly
    networks:
      - name: Tenderly
        chainid: 137
        id: polygon-tenderly
        host:  https://rpc.tenderly.co/fork/9a37c945-f7cf-45c5-9c6b-2e473e412f56
        explorer: https://api.polygonscan.com/api

development:
- name: Polygon Fork
  id: polygon-fork
  cmd: ganache-cli
  host: http://127.0.0.1
  timeout: 120
  cmd_settings:
    port: 8545
    gas_limit: 20000000
    accounts: 10
    fork: polygon
